const SUCCESS = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const SERVICE_UNAVAILABLE = 503;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
 SUCCESS,
 CREATED,
 BAD_REQUEST,
 NOT_FOUND,
 SERVICE_UNAVAILABLE,
 INTERNAL_SERVER_ERROR
}